package com.web0zz.domain.model.launches

data class Launches(
    val id: String,
    val fairings: Fairings?,
    val launchesLinks: LaunchesLinks?,
    val staticFireDateUtc: String?,
    val staticFireDateUnix: Int?,
    val net: Boolean?,
    val window: Int?,
    val rocket: String?,
    val success: Boolean?,
    val failures: List<Failures>?,
    val details: String?,
    val crew: List<String>?,
    val ships: List<String>?,
    val capsules: List<String>?,
    val payloads: List<String>?,
    val launchpad: String?,
    val flightNumber: Int?,
    val name: String?,
    val dateUtc: String?,
    val dateUnix: Int?,
    val dateLocal: String?,
    val datePrecision: String?,
    val upcoming: Boolean?,
    val cores: List<LaunchesCores>?,
    val autoUpdate: Boolean?,
    val tbd: Boolean?,
    val launchLibraryId: String?
)
