package com.web0zz.domain.model

data class Launches(
    val id: String,
    val fairings: Fairings,
    val links: Links,
    val staticFireDateUtc: String,
    val staticFireDateUnix: Int,
    val net: Boolean,
    val window: Int,
    val rocket: String,
    val success: Boolean,
    val failures: List<Failures>,
    val details: String,
    val crew: List<String>,
    val ships: List<String>,
    val capsules: List<String>,
    val payloads: List<String>,
    val launchpad: String,
    val flightNumber: Int,
    val name: String,
    val dateUtc: String,
    val dateUnix: Int,
    val dateLocal: String,
    val datePrecision: String,
    val upcoming: Boolean,
    val cores: List<Cores>,
    val autoUpdate: Boolean,
    val tbd: Boolean,
    val launchLibraryId: String
)
